exclude: ".git"

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.41.0
      hooks:
      - id: markdownlint
        args:
          - "README.md"
    - repo: local
      hooks:
      - id: demo-pre-commit
        name: demo-pre-commit
        entry: python3 ./scripts/pre-commit-hook.py
        language: python
        verbose: true
